=== Sable/clara/clara-emptyext/tests/abcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test*)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!ELEMENT ajc-test ((abckeywords)*, compile, (compile | inc-compile | run | ajcrun | abckeywords )*)>
   <!ATTLIST ajc-test num CDATA #IMPLIED >
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >
   <!ATTLIST ajc-test abccomment CDATA #IMPLIED>

   <!ELEMENT compile (dir-changes*,file*,(ajcmessage | message | jamessage)*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >
   <!ATTLIST compile inpath CDATA #IMPLIED >
   <!ATTLIST compile xlintfile CDATA #IMPLIED >
   <!ATTLIST compile outjar CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >

   <!ELEMENT ajcrun (dir-changes*,message*)>
   <!ATTLIST ajcrun class CDATA #REQUIRED >
   <!ATTLIST ajcrun skipTester CDATA #IMPLIED >
   <!ATTLIST ajcrun vm CDATA #IMPLIED >
   <!ATTLIST ajcrun options CDATA #IMPLIED >
   <!ATTLIST ajcrun errStreamIsError CDATA #IMPLIED >
   <!ATTLIST ajcrun outStreamIsError CDATA #IMPLIED >

   <!ELEMENT abckeywords (ganesh | aske | oege | laurie | sascha | pavel | julian | jennifer | nate | abclimitation | introductions | polyglot | soot | skip | warningbehaviour )*>
   
   <!ELEMENT ganesh EMPTY>
   <!ELEMENT aske EMPTY>
   <!ELEMENT oege EMPTY>
   <!ELEMENT laurie EMPTY>
   <!ELEMENT sascha EMPTY>
   <!ELEMENT pavel EMPTY>
   <!ELEMENT julian EMPTY>
   <!ELEMENT jennifer EMPTY>
   <!ELEMENT nate EMPTY>
   <!ELEMENT abclimitation EMPTY>
   <!ELEMENT introductions EMPTY>
   <!ELEMENT polyglot EMPTY>
   <!ELEMENT soot EMPTY>
   <!ELEMENT warningbehaviour EMPTY>

   <!ELEMENT file (#PCDATA)>
   <!ATTLIST file path CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT ajcmessage (source*)>
   <!ATTLIST ajcmessage kind (abort | fail | error | warning | info | Xlint | ignore ) #REQUIRED >
   <!ATTLIST ajcmessage line CDATA #IMPLIED >
   <!ATTLIST ajcmessage text CDATA #IMPLIED >
   <!ATTLIST ajcmessage file CDATA #IMPLIED >
   <!ATTLIST ajcmessage details CDATA #IMPLIED >

   <!ELEMENT jamessage (source*)>
   <!ATTLIST jamessage kind (abort | fail | error | warning | info | Xlint | ignore ) #REQUIRED >
   <!ATTLIST jamessage line CDATA #IMPLIED >
   <!ATTLIST jamessage text CDATA #IMPLIED >
   <!ATTLIST jamessage file CDATA #IMPLIED >
   <!ATTLIST jamessage details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run | ajcrun ) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >

=== Sable/clara/trunk/clara/tests/claraTests.xml
<!-- <!DOCTYPE suite SYSTEM "../tests/abcTestSuite.dtd"> -->

<!--

***** ABC Boys and Girls .... Rules for editing this file. ******

1)  you may add an abccomment to an ajc-test entry,  here is an
    example I have added to the first entry of abcTests.xml.

    Note that this is INSIDE that <ajc-test num="1" ajc-test ....> tag.

<ajc-test num="2" dir="base/test100"
      abccomment="I have put this comment in as a test, and this is a very
         long one over multiple lines too. LJH"
      title="static and non-static before methods -  one file"
      keywords="from-base">
        <compile files="Driver.java"/>
        <run class="Driver"/>
    </ajc-test>

2)  if you want to change any of the <message ... /> items because they don't
    correspond to the errors/warnings that we expect from abc,  you
    should.

      (a) RENAME ALL existing <message ... /> items to
                              <ajcmessage ... />.

      (b) INSERT new <message .../> items corresponding to what you
               expect from abc.  (note that the testHarness seems to
               only handle one message per line number)

      (c) INSERT an abccomment into the <ajc-test num="3" ... /> tag to describe
             what you changed and why

3) if you want to change an entry from one that was supposed to run, to
     one that should exit with compile-time errors ...

      (a) REPLACE the <compile files="foo.java"/>  
          with an entry as follows.  Note that the <compile .../> entry
          is replaced with <compile>  .... </compile>, where the first
          entry is an ajcmessage with kind="ignore" and then your
          real messages.
 
                      <compile files="foo.java">
                         <ajcmessage kind="ignore"/>
                         <message kind="error" line="xx"/>
                         <message kind="warning" line="yy"/>
                       </compile>

       (b) CHANGE  the <run .... > to <ajcrun ....>

       (c) INSERT an abccomment to say what you changed and why
           
     Here is an example:

     original entry:

     <ajc-test num="4" dir="pureJava" title="Using 'aspect' as identifier is legal"
      keywords="from-java,purejava">
        <compile files="KeywordAspect.java"/>
        <crun class="KeywordAspect" />
     </ajc-test>


     new entry:

     <ajc-test num="5" dir="pureJava" title="Using 'aspect' as identifier is legal"
      abccomment="abc doesn't allow keywords 
                      need to allow for syntax error. LJH "
      keywords="from-java,purejava">
        <compile files="KeywordAspect.java">
          <ajcmessage kind="ignore" />
          <message kind="error" line="7"/> 
        </compile>
        <ajcrun class="KeywordAspect" />
    </ajc-test>

4) A new set/style of keywords is available for <ajctest/> tags. The
     attribute "keywords" is still valid, in addition each <ajctest>
     can contain a <abckeywords> element, which in turn contains 
     keywords *in the form of further elements*. This allows keywords
     to be taken from a pre-defined list and easily verified.

     An example to make it clear - 
     
         <ajc-test num="6" dir="base/test100"
	        abccomment="I have put this comment in as a test, and this is a very
	       long one over multiple lines too. LJH"
	         title="static and non-static before methods - one file"
		 keywords="from-base">
		<compile files="Driver.java"/>
		<run class="Driver"/>
		<abckeywords>
		     <laurie/>
		     <pavel/>
		</abckeywords>
         </ajc-test>
	 

     For now, the keywords available as elements in the DTD are:
     ganesh, aske, oege, laurie, sascha, pavel, julian, jennifer,
     abclimitations, introductions, polyglot, soot.

     To extend the DTD with additional keywords as the need arises,
     (a) EDIT the line starting with <!ELEMENT abckeywords ...> so that
         the enumeration of possible child elements includes the new
	 keyword
     (b) INSERT a line declaring the new element below. It should have
         the form <!ELEMENT new_keyword EMPTY>.

-->

<!--
  known keywords:
 
  knownLimitation     Accepted limitation of current implementation (fails)
  purejava            Sources compile under javac as well
  broken-test         ??
  messages-vary       one of many (usually two) test specs that differ only in 
                      messages expected by the different compilers.
                      Currently ajc 1.0 tests are in ajcTests10.xml,
                      so there may only be one copy marked "messages-vary" here.
  new-messages-vary   like messages-vary, except need to make ajcTest10 variant

  fail-{...}          test fails in some configuration
  fail-unimplmented   eajc throwing "unimplemented" exception
  fail-commandLine    fails in ajc on command line (move to ajcTestsBroken.xml)
  fail-in-eclipse     fail when harness in run from inside eclipse
  fail-publicType     now fixed - no longer presenting error for public type in wrong file

  from-{file}         from original {file}.txt for file in
                      java, bigjava, resolved_1*, 14tests, errors, design, base... 

  incremental-test    uses inc-compile step
  command-error       command-line error test

  knownLimitation-ajctaskCompiler
                      Accepted limitation of the AjcTaskCompilerCommand wrapper
  knownLimitation-ajdeCompiler
                      Accepted limitation of the AJDE CompileCommand wrapper
                      
  poorErrorMessages   test case passes but errors produced by compiler could do with
                      improvement                      
                      
  Test titles:
  
  Titles should be unique and not change, and related tests should have the 
  same title prefix.  This permits us to automatically compare the test results 
  from different versions (and suites), and to see related differences together.
  
  -->

<suite>

   <ajc-test num="1302" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-insensitive stage">
        <compile files="FlowIns.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="12"/>
	    	<message kind="warning" line="13"/>
		</compile>
		<run class="FlowIns"/>
    </ajc-test>
    		    		
    <ajc-test num="1303" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-insensitive stage, test 2">
        <compile files="FlowIns2.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="20"/>
	    	<message kind="warning" line="21"/>
		</compile>
    </ajc-test>
    
    <ajc-test num="1304" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-sensitive intraprocedural stage, Test1">
        <compile files="IntraFlowSens1.java,AB.java,AbstractTest.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa-nsa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="41"/>
	    	<message kind="warning" line="43"/>
	    	<message kind="warning" line="48"/>
	    	<message kind="warning" line="52"/>
	    	<message kind="warning" line="59"/>
	    	<message kind="warning" line="66"/>
	    	<message kind="warning" line="68"/>
	    	<message kind="warning" line="73"/>
	    	<message kind="warning" line="77"/>
		</compile>
    </ajc-test>
    
    <ajc-test num="1305" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-sensitive intraprocedural stage, Test2">
        <compile files="IntraFlowSens2.java,AB.java,AbstractTest.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa-nsa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="11"/>
	    	<message kind="warning" line="13"/>
		</compile>
    </ajc-test>
    
    <ajc-test num="1306" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-sensitive intraprocedural stage, Test3">
        <compile files="IntraFlowSens3.java,AB.java,AbstractTest.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa-nsa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="13"/>
	    	<message kind="warning" line="15"/>
	    	<message kind="warning" line="27"/>
	    	<message kind="warning" line="29"/>
		</compile>
    </ajc-test>
    
    <ajc-test num="1307" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-sensitive intraprocedural stage, Test4 (tainting)">
        <compile files="IntraFlowSens4.java,AB.java,AbstractTest.java" options="-ext,ca.mcgill.sable.clara.tm,-static-analyses,quick-osa-nsa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="9"/>
		</compile>
    </ajc-test>

    <ajc-test num="1308" dir="tracematches/wp-opt"
        title="Tracematches (wp-tmopt): flow-sensitive intraprocedural stage, FailSafeIterFI">
        <compile files="FailSafeIterFI.java" options="-ext,ca.mcgill.sable.clara.tm,-w,-static-analyses,quick-osa-nsa,-warn-about-individual-shadows,-cp,../../abc/lib/abc-runtime.jar:../../abc/lib/abc-testing.jar,+soot,-pp,-no-bodies-for-excluded,-soot">
	    	<message kind="warning" line="38"/>
	    	<message kind="warning" line="39"/>
	    	<message kind="warning" line="40"/>
	    	<message kind="warning" line="46"/>
